src/assets/svg/checked-icon.svg, src/assets/svg/unchecked-icon.svg, src/components/Checkbox/Checkbox.style.ts, src/components/Checkbox/Checkbox.tsx, src/components/Tab/Tab.style.ts, src/components/Tab/Tab.tsx, src/components/Tabs/Tabs.style.ts, src/components/Tabs/Tabs.tsx, src/components/Toggle/Toggle.style.ts, src/components/Toggle/Toggle.tsx, src/components/ToggleGroup/ToggleGroup.style.ts, src/components/ToggleGroup/ToggleGroup.tsx, src/stories/Checkbox.stories.tsx, src/stories/Tabs.stories.tsx, src/stories/ToggleGroup.stories.tsx
=> Checkbox, Tab, Tabs, ToggleGroup, Toggle 컴포넌트 추가

src/components/Box/Box.style.ts, src/components/Box/Box.tsx, src/components/Center/Center.style.ts, src/components/Center/Center.tsx, src/components/Flex/Flex.style.ts, src/components/Flex/Flex.tsx, src/stories/Box.stories.tsx, src/stories/Center.stories.tsx, src/stories/Flex.stories.tsx
=> Box, Center, Flex 컴포넌트 생성

.storybook/main.ts, package-lock.json, package.json, src/assets/svg/empty-star.svg, src/assets/svg/filled-star.svg, src/assets/svg/half-empty-left-star.svg, src/assets/svg/half-empty-right-star.svg, src/assets/svg/half-filled-left-star.svg, src/assets/svg/half-filled-right-star.svg, src/components/StarRating/StarRating.style.ts, src/components/StarRating/StarRating.tsx, src/components/StarRating/useStarRating.ts, src/stories/StarRating.stories.ts, webpack.config.js
=> StarRating 컴포넌트 추가

.github/workflows/chromatic.yml, .gitignore, package-lock.json, package.json
스토리북 chromatic 자동 배포 기능 추가
close #5
=> 스토리북 chromatic 자동 배포 기능 추가

package-lock.json, package.json
=> npm 배포 업데이트

src/components/StarRating/StarRating.tsx, src/hooks/useStarRating.ts, src/stories/StarRating.stories.tsx
=> StarRating 버그수정 및 기능 추가

src/components/MenuItem/MenuItem.tsx, src/components/RadioButton/RadioButton.tsx, src/stories/Menu.stories.tsx
RadioButton 첫번째 옵션 선택된 채로 랜더링 되게 수정했습니당! 
close #27
=> RadioButton 첫번째 옵션 선택된채로 랜더링 되게 수정

src/hooks/useOverlay.ts, src/index.tsx, src/stories/Menu.stories.tsx, src/stories/Modal.stories.tsx, src/stories/Toast.stories.tsx
=> 열고 닫고 토글할 수 있는 로직 훅으로 생성(useOverlay)

README.md, package-lock.json, package.json, src/stories/Menu.stories.tsx
=> npm 배포 v1.1.0

package-lock.json, package.json, src/index.tsx
=> npm 배포 v1.1.1

src/components/MenuItem/MenuItem.style.ts, src/components/MenuItem/MenuItem.tsx, src/stories/Menu.stories.tsx
=> MenuItem children받도록 수정, hovert시 트렌지션

src/components/Box/Box.style.ts, src/components/Box/Box.tsx, src/components/Center/Center.tsx, src/components/Flex/Flex.style.ts, src/components/Flex/Flex.tsx, src/components/Tabs/Tabs.style.ts, src/index.tsx
Flex, Center, Box 컴포넌트 attributes 추가
Flex margin, padding, border 추가
close #40
=> Flex, Center, Box 컴포넌트 고도화

src/components/StarRatingInput/StarRatingInput.style.ts, src/components/StarRatingInput/StarRatingInput.tsx, src/stories/StarRatingInput.stories.tsx
StarRating -> StarRatingInput 컴포넌트 네이밍 수정
close #43
=> StarRating -> StarRatingInput 컴포넌트 네이밍 수정

README.md, package-lock.json, package.json, src/index.tsx
=> npm 배포 v1.1.2

package-lock.json, package.json
=> npm v1.1.4 배포

src/components/Badge/Badge.style.ts, src/components/ImageCarousel/ImageCarousel.style.ts, src/components/ImageCarousel/ImageCarousel.tsx, src/hooks/useImageCarousel.ts, src/stories/ImageCarousel.stories.tsx, src/utils/number.ts
<br>
- 이미지 슬라이더 컴포넌트 구현
- 드래그해서 이미지 사이를 움직일 수 있다
- `< | >` 버튼을 클릭해서 이미지 사이를 움직일 수 있다 
- 하단 점을 클릭해서 원하는 이미지에 갈 수 있다
<br>
close #47
=> ImageCarousel 컴포넌트 구현

package-lock.json, package.json, src/components/ImageCarousel/ImageCarousel.style.ts, src/index.tsx
=> npm v1.1.5 배포

src/components/Tab/Tab.style.ts
- 클릭했을 때 border-bottom이 추가되면서 하단 정보가 움직이게 된다
<br>
close #55
=> Tab 컴포넌트 수정

src/components/MenuItem/MenuItem.style.ts
=> MenuItem 폰트 사이즈 수정

src/components/ImageCarousel/ImageCarousel.style.ts
- image carousel 화살표에 cursor: pointer 추가
<br>
close #56
=> ImageCarousel 컴포넌트 수정

src/components/Toggle/Toggle.style.ts
- 폰트 사이즈 medium에서 small로 변경
<br>
close #57
=> Toggle 컴포넌트 수정

src/components/FloatingButton/FloatingButton.style.ts
=> FloatingButton 컴포넌트 수정

src/components/Tab/Tab.tsx, src/components/Tabs/Tabs.tsx, src/components/Toggle/Toggle.tsx, src/components/ToggleGroup/ToggleGroup.tsx, src/hooks/useSelect.ts, src/stories/Tabs.stories.tsx, src/stories/ToggleGroup.stories.tsx
useSelect 추가
Toggle, Tabs 사용 방법 변경
=> feat: Toggle, Tabs 컴포넌트 사용 Hook 추가

src/stories/Tabs.stories.tsx
스토리북 Tab 컴포넌트 동작 오류 해결
close #68
=> fix: 스토리북 Tab 컴포넌트 동작 오류 해결

README.md, package-lock.json, package.json, src/stories/Tabs.stories.tsx
=> npm v1.1.8 배포

src/components/Tab/Tab.style.ts, src/components/Tab/Tab.tsx, src/components/Tabs/Tabs.style.ts, src/components/Tabs/Tabs.tsx, src/components/Toggle/Toggle.style.ts, src/components/Toggle/Toggle.tsx, src/components/ToggleGroup/ToggleGroup.style.ts, src/components/ToggleGroup/ToggleGroup.tsx, src/hooks/useSelect.ts, src/stories/Tabs.stories.tsx, src/stories/ToggleGroup.stories.tsx
- ToggleGroup에서 Toggle을 클릭할 때마다 사이즈가 미세하게 변한다
- Tabs에서 클릭했을 때의 폰트 사이즈와 클릭하기 전의 폰트 사이즈가 다르다
- useSelect에 현재 선택된 초기 값을 넘겨줄 수 있어야 한다
close #73
=> ToggleGroup, Tabs 컴포넌트 버그 및 useSelect 커스텀 훅 수정

README.md, package-lock.json, package.json
- ToggleGroup, Tabs 컴포넌트 버그 및 useSelect 커스텀 훅 수정
#23
=> npm v1.1.10 배포

package-lock.json, package.json, src/components/Tabs/Tabs.tsx, src/components/ToggleGroup/ToggleGroup.tsx, src/hooks/useSelect.ts, src/hooks/useStarRatingInput.ts, src/index.tsx, src/stories/StarRatingInput.stories.tsx, src/stories/Tabs.stories.tsx, src/stories/ToggleGroup.stories.tsx
- useSelect export 
- useStarRating에서 useStarRatingInput으로 변경
#23
=> npm v1.1.11 배포

src/components/Skeleton/Skeleton.style.ts, src/components/Skeleton/Skeleton.tsx
- Skeleton 컴포넌트가 attributes를 받을 수 있도록 수정
<br>
close #77
=> Skeleton 컴포넌트 수정

README.md, package-lock.json, package.json
=> npm v1.1.12 배포

src/components/SVGCarousel/SVGCarousel.style.ts, src/components/SVGCarousel/SVGCarousel.tsx, src/stories/SVGCarousel.stories.tsx
=> SVGCarousel 컴포넌트 추가

README.md, package-lock.json, package.json
npm v1.1.13 배포
- SVGCarousel 컴포넌트 추가
#23
=> npm v1.1.13 배포

package-lock.json, package.json, src/index.tsx
=> npm v1.1.14 배포

package-lock.json, package.json, src/components/ImageCarousel/ImageCarousel.style.ts, src/components/ImageCarousel/ImageCarousel.tsx, src/components/SVGCarousel/SVGCarousel.tsx
- ImageCarousel에 드래그 여부 옵션 추가
<br>
#23
=> npm v1.1.15 배포

src/styles/Theme.ts
Theme zIndex overlayPeak 추가
close #86
=> Theme zIndex overlayPeak 추가

README.md, package-lock.json, package.json
=> npm v1.1.16 배포

src/components/StarRatingInput/StarRatingInput.style.ts, src/components/StarRatingInput/StarRatingInput.tsx, src/stories/StarRatingInput.stories.tsx
- `cursor: pointer`로 변경
- `label`, `supporting text`를 받을 수 있도록 수정
<br>
close #88
=> StarRatingInput 컴포넌트 수정

src/components/Modal/Modal.style.ts
- `borderRadius` `8px`에서 `16px`로 변경
- `maxWidth` 속성 삭제
<br>
close #89
=> Modal 컴포넌트 수정

src/components/Input/Input.style.ts, src/components/Textarea/Textarea.style.ts
- Input, Textarea 포커스 스타일링 수정
<br>
close #92
=> Input, Textarea 컴포넌트 수정

src/components/Calendar/Calendar.tsx
- DateRangePicker 앞/뒤로 움직일 때 제대로 작동 안 하는 버그 해결
<br>
close #96
=> DateRangePicker 버그 해결

README.md, package-lock.json, package.json
=> npm v1.1.19 배포

package-lock.json, package.json, src/hooks/useStarRatingInput.ts, src/index.tsx
- useStarRatingInput 수정
- ImageUploadInput export
=> npm v1.1.20 배포

package-lock.json, package.json, src/components/ImageCarousel/ImageCarousel.style.ts, src/components/Modal/Modal.tsx, src/components/RadioButton/RadioButton.tsx
- ImageCarousel 컴포넌트 스타일 수정
- Modal 컴포넌트 attributes 받을 수 있도록 수정 
- RadioButton props jsdoc 설명 추가
=> npm v1.1.25 배포

README.md, package-lock.json, package.json
=> npm v1.1.26 배포

src/components/ImageUploadInput/ImageUploadInput.style.ts, src/components/ImageUploadInput/ImageUploadInput.tsx, src/components/Modal/Modal.style.ts
- Modal 컴포넌트 백드롭 `cursor: pointer`로 변경
<br>
- ImageUploadInput `overflowX: scroll` 추가
<br>
close #110
=> 컴포넌트 버그 수정

README.md, package-lock.json, package.json
- Modal 컴포넌트 백드롭 `cursor: pointer`로 변경
- ImageUploadInput `overflowX: scroll` 추가
=> npm v1.2.0 배포

src/components/Calendar/Day/Day.style.ts, src/components/Calendar/Day/Day.tsx, src/components/DateRangePicker/DateRangePicker.style.ts, src/types/index.ts
=> DateRangePicker 컴포넌트 수정

src/components/Tab/Tab.style.ts, src/components/Tab/Tab.tsx, src/components/Tabs/Tabs.style.ts, src/components/Tabs/Tabs.tsx, src/components/Toggle/Toggle.style.ts, src/components/Toggle/Toggle.tsx, src/components/ToggleGroup/ToggleGroup.style.ts, src/components/ToggleGroup/ToggleGroup.tsx
- 중복 되는 스타일 코드 리팩토링
- 기타 버그 수정
<br>
close #114
=> Toggle, Tab 관련 컴포넌트 리팩토링

README.md, package-lock.json, package.json, src/components/Center/Center.tsx, src/components/ImageUploadInput/ImageUploadInput.style.ts
- Layout 관련 컴포넌트 리팩토링
- Toggle, Tab 컴포넌트 리팩토링
- DateRangePicker 컴포넌트 반응형 css 추가
- 기타 버그 수정
=> npm v1.2.1 배포

src/components/MenuList/MenuList.tsx
-  MenuList 컴포넌트 div에서 ul 태그로 변경
close #120
=> MenuList 컴포넌트 수정

package-lock.json, package.json
=> npm v1.2.3 배포

package-lock.json, package.json, src/components/ImageCarousel/ImageCarousel.tsx
=> npm v1.2.4 배포

README.md, package-lock.json, package.json
- eslint 설정 수정 및 storybook a11y 애드온 추가
=> npm v1.2.5 배포

package-lock.json, package.json, src/components/ImageUploadInput/ImageUploadInput.style.ts, src/components/ImageUploadInput/ImageUploadInput.tsx, src/stories/ImageUploadInput.stories.tsx
=> npm v1.2.7 배포

src/components/Toast/Toast.style.ts, src/components/Toast/Toast.tsx
- Toast 내부에서 열고 닫음 관리
<br>
close #134
=> Toast 컴포넌트 수정

README.md, package-lock.json, package.json
=> npm v1.2.9 배포

src/hooks/useOverlay.ts, src/stories/Modal.stories.tsx
modal open 상태로 시작하는 경우 모달이 닫히지 않는 문제 해결
=> useOverlay 수정

README.md, package-lock.json, package.json
- useOverlay 훅 수정
- 스토리북 Modal 스토리 추가
=> npm v1.2.10 배포

README.md, package-lock.json, package.json
=> npm v1.2.11 배포

src/assets/svg/half-empty-left-star.svg, src/assets/svg/half-empty-right-star.svg, src/assets/svg/half-filled-left-star.svg, src/assets/svg/half-filled-right-star.svg, src/components/StarRatingInput/StarRatingInput.style.ts, src/components/StarRatingInput/StarRatingInput.tsx, src/hooks/useStarRatingInput.ts, src/stories/StarRatingInput.stories.tsx
=> StarRating 컴포넌트 재구축

src/hooks/useStarRatingInput.ts
useStarRatingInput onClick 인자 롤백
close #144
=> useStarRatingInput onClick 인자만 롤백

src/components/StarRatingInput/StarRatingInput.style.ts
=> StarRatingInput 깜빡임 이슈 수정

README.md, package-lock.json, package.json
StarRatingInput 컴포넌트 별 깜빡임 이슈 수정
#23
=> npm v1.2.16 배포

package-lock.json, package.json, src/components/StarRatingInput/StarRatingInput.tsx
=> npm v1.2.17 배포

package-lock.json, package.json, src/components/ImageUploadInput/ImageUploadInput.tsx
=> npm v1.2.20 배포

src/components/SVGCarouselModal/SVGCarouselModal.style.ts, src/components/SVGCarouselModal/SVGCarouselModal.tsx, src/index.tsx, src/stories/SVGCarouselModal.stories.tsx
=> SVGCarouselModal 추가

README.md, package-lock.json, package.json
=> npm v1.2.22 배포

src/components/SVGCarouselModal/SVGCarouselModal.style.ts, src/components/SVGCarouselModal/SVGCarouselModal.tsx, src/stories/SVGCarouselModal.stories.tsx
SVGCarousel boxStyling css 수정, dots Styling 수정
=> SVGCarousel boxStyling css 수정, dots Styling 수정

package-lock.json, package.json
=> npm v1.2.25 배포

src/components/SVGCarouselModal/SVGCarouselModal.style.ts, src/components/SVGCarouselModal/SVGCarouselModal.tsx, src/stories/SVGCarouselModal.stories.tsx
SVGCarouselModal 버튼 갭, dots 갭 추가
=> SVGCarouselModal 버튼 갭, dots 갭 추가

README.md, package-lock.json, package.json
=> npm v1.3.0 배포

src/components/StarRatingInput/StarRatingInput.tsx, src/stories/StarRatingInput.stories.tsx
=> 모바일 환경에서 StarRatingInput 호버 문제 수정

src/stories/StarRatingInput.stories.tsx
StarRatingInput storybook 오류 수정
=> StarRatingInput storybook 오류 수정

README.md, package-lock.json, package.json
=> build: npm v1.3.1 배포

src/components/StarRatingInput/StarRatingInput.style.ts, src/components/StarRatingInput/StarRatingInput.tsx, src/hooks/useDebounce.ts, src/hooks/useStarRatingInput.ts
별점컴포넌트 호버해두고 마우스 빠르게 움직이면 이상해지는거 수정함
state 일부 ref로 수정하고 디바운스걸었음.
close #167
=> StarRating 컴포넌트 개선

src/components/GeneralCarousel/Dots.tsx, src/components/GeneralCarousel/GeneralCarousel.tsx, src/hooks/useGeneralCarousel.ts
GeneralCarousel 컴포넌트 이벤트 버블링 방지 코드 추가
=> Carousel 컴포넌트 코드 개선

src/components/GeneralCarousel/GeneralCarousel.tsx
GeneralCarousel 컴포넌트 children prop 추가
children이 필요한 경우가 있더군요..?
close #165
=> Carousel 컴포넌트 리팩토링

package.json
=> npm v1.3.7 배포
